import { suggestAbilityScores } from './rules2024';
import type { PregenCharacter } from './types';

export const PREGENERATED_CHARACTERS: PregenCharacter[] = [
  {
    id: 'sahlumerin-penitent',
    name: 'Arel Voss',
    summary: 'Human cleric, failed temple initiate, trained by doctrine and disgrace.',
    input: {
      name: 'Arel Voss',
      classId: 'cleric',
      speciesId: 'human',
      backgroundId: 'acolyte',
      backstoryId: 'failed_initiate',
      nationalityId: 5,
      religionId: 11,
      abilityScores: suggestAbilityScores('cleric', 'acolyte'),
      skillProficiencies: ['medicine', 'persuasion'],
    },
  },
  {
    id: 'kozesleli-survivor',
    name: 'Temur Ash-Knee',
    summary: 'Orc fighter, battlefield survivor from the khaganate frontier.',
    input: {
      name: 'Temur Ash-Knee',
      classId: 'fighter',
      speciesId: 'orc',
      backgroundId: 'soldier',
      backstoryId: 'battlefield_witness',
      nationalityId: 9,
      religionId: 7,
      abilityScores: suggestAbilityScores('fighter', 'soldier'),
      skillProficiencies: ['athletics', 'perception'],
    },
  },
  {
    id: 'nelkug-castaway',
    name: 'Mira Qel',
    summary: 'Halfling rogue, shipwrecked pilgrim with quick hands and quicker judgment.',
    input: {
      name: 'Mira Qel',
      classId: 'rogue',
      speciesId: 'halfling',
      backgroundId: 'sailor',
      backstoryId: 'shipwrecked_pilgrim',
      nationalityId: 10,
      religionId: 15,
      abilityScores: suggestAbilityScores('rogue', 'sailor'),
      skillProficiencies: ['acrobatics', 'investigation', 'perception', 'stealth'],
    },
  },
  {
    id: 'ceruan-hidden-blood',
    name: 'Ser Caldus Neth',
    summary: 'Dragonborn paladin, exiled noble heir traveling as a penitent.',
    input: {
      name: 'Ser Caldus Neth',
      classId: 'paladin',
      speciesId: 'dragonborn',
      backgroundId: 'noble',
      backstoryId: 'exiled_heir',
      nationalityId: 11,
      religionId: 17,
      abilityScores: suggestAbilityScores('paladin', 'noble'),
      skillProficiencies: ['athletics', 'religion'],
    },
  },
  {
    id: 'khundush-omen',
    name: 'Nessa Underleaf',
    summary: 'Gnome druid, sent into the wild after an omen turned the village against her.',
    input: {
      name: 'Nessa Underleaf',
      classId: 'druid',
      speciesId: 'gnome',
      backgroundId: 'guide',
      backstoryId: 'wild_omen',
      nationalityId: 15,
      religionId: 1,
      abilityScores: suggestAbilityScores('druid', 'guide'),
      skillProficiencies: ['nature', 'perception'],
    },
  },
  {
    id: 'shaterian-escapee',
    name: 'Ilyon Reed',
    summary: 'Elf wizard, escaped prisoner whose arcane training survived captivity.',
    input: {
      name: 'Ilyon Reed',
      classId: 'wizard',
      speciesId: 'elf',
      backgroundId: 'sage',
      backstoryId: 'escaped_prisoner',
      nationalityId: 1,
      religionId: 11,
      abilityScores: suggestAbilityScores('wizard', 'sage'),
      skillProficiencies: ['arcana', 'investigation'],
    },
  },
];
