import { suggestAbilityScores } from './rules2024';
import type { PregenCharacter } from './types';

export const PREGENERATED_CHARACTERS: PregenCharacter[] = [
  {
    id: 'sahlumerin-penitent',
    name: 'Arel Voss',
    summary: 'Human cleric — a Duhi Troupe washout drilled in doctrine and battlefield rites.',
    input: {
      name: 'Arel Voss',
      gender: 'male',
      classId: 'cleric',
      speciesId: 'human',
      backgroundId: 'acolyte',
      nationalityId: 5,
      religionId: 11,
      abilityScores: suggestAbilityScores('cleric', 'acolyte'),
      skillProficiencies: ['medicine', 'persuasion'],
    },
  },
  {
    id: 'kozesleli-survivor',
    name: 'Temur Ash-Knee',
    summary: 'Orc fighter — a Duhi Troupe washout whose weapon drills never left him.',
    input: {
      name: 'Temur Ash-Knee',
      gender: 'male',
      classId: 'fighter',
      speciesId: 'orc',
      backgroundId: 'soldier',
      nationalityId: 9,
      religionId: 7,
      abilityScores: suggestAbilityScores('fighter', 'soldier'),
      skillProficiencies: ['athletics', 'perception'],
    },
  },
  {
    id: 'nelkug-castaway',
    name: 'Mira Qel',
    summary: 'Halfling rogue — a Duhi Troupe washout with quick hands and quicker judgment.',
    input: {
      name: 'Mira Qel',
      gender: 'female',
      classId: 'rogue',
      speciesId: 'halfling',
      backgroundId: 'sailor',
      nationalityId: 10,
      religionId: 15,
      abilityScores: suggestAbilityScores('rogue', 'sailor'),
      skillProficiencies: ['acrobatics', 'investigation', 'perception', 'stealth'],
    },
  },
  {
    id: 'ceruan-hidden-blood',
    name: 'Ser Caldus Neth',
    summary: 'Dragonborn paladin — a Duhi Troupe washout carrying oath and martial forms.',
    input: {
      name: 'Ser Caldus Neth',
      gender: 'male',
      classId: 'paladin',
      speciesId: 'dragonborn',
      backgroundId: 'noble',
      nationalityId: 11,
      religionId: 17,
      abilityScores: suggestAbilityScores('paladin', 'noble'),
      skillProficiencies: ['athletics', 'religion'],
    },
  },
  {
    id: 'khundush-omen',
    name: 'Nessa Underleaf',
    summary: 'Gnome druid — a Duhi Troupe washout who kept the primal rites they taught her.',
    input: {
      name: 'Nessa Underleaf',
      gender: 'female',
      classId: 'druid',
      speciesId: 'gnome',
      backgroundId: 'guide',
      nationalityId: 15,
      religionId: 1,
      abilityScores: suggestAbilityScores('druid', 'guide'),
      skillProficiencies: ['nature', 'perception'],
    },
  },
  {
    id: 'shaterian-escapee',
    name: 'Ilyon Reed',
    summary: 'Elf wizard — a Duhi Troupe washout whose arcane drills outlasted the facility.',
    input: {
      name: 'Ilyon Reed',
      gender: 'male',
      classId: 'wizard',
      speciesId: 'elf',
      backgroundId: 'sage',
      nationalityId: 1,
      religionId: 11,
      abilityScores: suggestAbilityScores('wizard', 'sage'),
      skillProficiencies: ['arcana', 'investigation'],
    },
  },
];
